// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: menu.proto

package menu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMenuItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MenuItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuItemsResponse) Reset() {
	*x = GetMenuItemsResponse{}
	mi := &file_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemsResponse) ProtoMessage() {}

func (x *GetMenuItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemsResponse.ProtoReflect.Descriptor instead.
func (*GetMenuItemsResponse) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{0}
}

func (x *GetMenuItemsResponse) GetItems() []*MenuItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *MenuItem              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuItemRequest) Reset() {
	*x = UpdateMenuItemRequest{}
	mi := &file_menu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuItemRequest) ProtoMessage() {}

func (x *UpdateMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMenuItemRequest) GetItem() *MenuItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *MenuItem              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMenuItemRequest) Reset() {
	*x = CreateMenuItemRequest{}
	mi := &file_menu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuItemRequest) ProtoMessage() {}

func (x *CreateMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuItemRequest.ProtoReflect.Descriptor instead.
func (*CreateMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMenuItemRequest) GetItem() *MenuItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMenuItemRequest) Reset() {
	*x = DeleteMenuItemRequest{}
	mi := &file_menu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMenuItemRequest) ProtoMessage() {}

func (x *DeleteMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMenuItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteMenuItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MenuItem struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PreviewDescription  string                 `protobuf:"bytes,3,opt,name=previewDescription,proto3" json:"previewDescription,omitempty"`
	DetailedDescription string                 `protobuf:"bytes,4,opt,name=detailedDescription,proto3" json:"detailedDescription,omitempty"`
	Time                int64                  `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	Price               int64                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	Category            string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_menu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{4}
}

func (x *MenuItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MenuItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItem) GetPreviewDescription() string {
	if x != nil {
		return x.PreviewDescription
	}
	return ""
}

func (x *MenuItem) GetDetailedDescription() string {
	if x != nil {
		return x.DetailedDescription
	}
	return ""
}

func (x *MenuItem) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *MenuItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MenuItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

var File_menu_proto protoreflect.FileDescriptor

const file_menu_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"menu.proto\x12\x04menu\x1a\x1bgoogle/protobuf/empty.proto\"<\n" +
	"\x14GetMenuItemsResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.menu.MenuItemR\x05items\";\n" +
	"\x15UpdateMenuItemRequest\x12\"\n" +
	"\x04item\x18\x01 \x01(\v2\x0e.menu.MenuItemR\x04item\";\n" +
	"\x15CreateMenuItemRequest\x12\"\n" +
	"\x04item\x18\x01 \x01(\v2\x0e.menu.MenuItemR\x04item\"'\n" +
	"\x15DeleteMenuItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd6\x01\n" +
	"\bMenuItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x12previewDescription\x18\x03 \x01(\tR\x12previewDescription\x120\n" +
	"\x13detailedDescription\x18\x04 \x01(\tR\x13detailedDescription\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x03R\x04time\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x03R\x05price\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory2\xa6\x02\n" +
	"\vMenuService\x12B\n" +
	"\fGetMenuItems\x12\x16.google.protobuf.Empty\x1a\x1a.menu.GetMenuItemsResponse\x12E\n" +
	"\x0eUpdateMenuItem\x12\x1b.menu.UpdateMenuItemRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\x0eCreateMenuItem\x12\x1b.menu.CreateMenuItemRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\x0eDeleteMenuItem\x12\x1b.menu.DeleteMenuItemRequest\x1a\x16.google.protobuf.EmptyB\x18Z\x16shared/proto/menu;menub\x06proto3"

var (
	file_menu_proto_rawDescOnce sync.Once
	file_menu_proto_rawDescData []byte
)

func file_menu_proto_rawDescGZIP() []byte {
	file_menu_proto_rawDescOnce.Do(func() {
		file_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_menu_proto_rawDesc), len(file_menu_proto_rawDesc)))
	})
	return file_menu_proto_rawDescData
}

var file_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_menu_proto_goTypes = []any{
	(*GetMenuItemsResponse)(nil),  // 0: menu.GetMenuItemsResponse
	(*UpdateMenuItemRequest)(nil), // 1: menu.UpdateMenuItemRequest
	(*CreateMenuItemRequest)(nil), // 2: menu.CreateMenuItemRequest
	(*DeleteMenuItemRequest)(nil), // 3: menu.DeleteMenuItemRequest
	(*MenuItem)(nil),              // 4: menu.MenuItem
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_menu_proto_depIdxs = []int32{
	4, // 0: menu.GetMenuItemsResponse.items:type_name -> menu.MenuItem
	4, // 1: menu.UpdateMenuItemRequest.item:type_name -> menu.MenuItem
	4, // 2: menu.CreateMenuItemRequest.item:type_name -> menu.MenuItem
	5, // 3: menu.MenuService.GetMenuItems:input_type -> google.protobuf.Empty
	1, // 4: menu.MenuService.UpdateMenuItem:input_type -> menu.UpdateMenuItemRequest
	2, // 5: menu.MenuService.CreateMenuItem:input_type -> menu.CreateMenuItemRequest
	3, // 6: menu.MenuService.DeleteMenuItem:input_type -> menu.DeleteMenuItemRequest
	0, // 7: menu.MenuService.GetMenuItems:output_type -> menu.GetMenuItemsResponse
	5, // 8: menu.MenuService.UpdateMenuItem:output_type -> google.protobuf.Empty
	5, // 9: menu.MenuService.CreateMenuItem:output_type -> google.protobuf.Empty
	5, // 10: menu.MenuService.DeleteMenuItem:output_type -> google.protobuf.Empty
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_menu_proto_init() }
func file_menu_proto_init() {
	if File_menu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_menu_proto_rawDesc), len(file_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_menu_proto_goTypes,
		DependencyIndexes: file_menu_proto_depIdxs,
		MessageInfos:      file_menu_proto_msgTypes,
	}.Build()
	File_menu_proto = out.File
	file_menu_proto_goTypes = nil
	file_menu_proto_depIdxs = nil
}
