// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: catalog.proto

package catalog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCatalogItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CatalogItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogItemsResponse) Reset() {
	*x = GetCatalogItemsResponse{}
	mi := &file_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogItemsResponse) ProtoMessage() {}

func (x *GetCatalogItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogItemsResponse.ProtoReflect.Descriptor instead.
func (*GetCatalogItemsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *GetCatalogItemsResponse) GetItems() []*CatalogItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateCatalogItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *CatalogItem           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCatalogItemRequest) Reset() {
	*x = UpdateCatalogItemRequest{}
	mi := &file_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCatalogItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCatalogItemRequest) ProtoMessage() {}

func (x *UpdateCatalogItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCatalogItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateCatalogItemRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateCatalogItemRequest) GetItem() *CatalogItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateCatalogItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *CatalogItem           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCatalogItemRequest) Reset() {
	*x = CreateCatalogItemRequest{}
	mi := &file_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCatalogItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCatalogItemRequest) ProtoMessage() {}

func (x *CreateCatalogItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCatalogItemRequest.ProtoReflect.Descriptor instead.
func (*CreateCatalogItemRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCatalogItemRequest) GetItem() *CatalogItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteCatalogItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCatalogItemRequest) Reset() {
	*x = DeleteCatalogItemRequest{}
	mi := &file_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCatalogItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCatalogItemRequest) ProtoMessage() {}

func (x *DeleteCatalogItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCatalogItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteCatalogItemRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteCatalogItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CatalogItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	ImgUrl        string                 `protobuf:"bytes,4,opt,name=imgUrl,proto3" json:"imgUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogItem) Reset() {
	*x = CatalogItem{}
	mi := &file_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogItem) ProtoMessage() {}

func (x *CatalogItem) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogItem.ProtoReflect.Descriptor instead.
func (*CatalogItem) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *CatalogItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CatalogItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CatalogItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CatalogItem) GetImgUrl() string {
	if x != nil {
		return x.ImgUrl
	}
	return ""
}

var File_catalog_proto protoreflect.FileDescriptor

const file_catalog_proto_rawDesc = "" +
	"\n" +
	"\rcatalog.proto\x12\acatalog\x1a\x1bgoogle/protobuf/empty.proto\"E\n" +
	"\x17GetCatalogItemsResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.catalog.CatalogItemR\x05items\"D\n" +
	"\x18UpdateCatalogItemRequest\x12(\n" +
	"\x04item\x18\x01 \x01(\v2\x14.catalog.CatalogItemR\x04item\"D\n" +
	"\x18CreateCatalogItemRequest\x12(\n" +
	"\x04item\x18\x01 \x01(\v2\x14.catalog.CatalogItemR\x04item\"*\n" +
	"\x18DeleteCatalogItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"g\n" +
	"\vCatalogItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x16\n" +
	"\x06imgUrl\x18\x04 \x01(\tR\x06imgUrl2\xcd\x02\n" +
	"\x0eCatalogService\x12K\n" +
	"\x0fGetCatalogItems\x12\x16.google.protobuf.Empty\x1a .catalog.GetCatalogItemsResponse\x12N\n" +
	"\x11UpdateCatalogItem\x12!.catalog.UpdateCatalogItemRequest\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\x11CreateCatalogItem\x12!.catalog.CreateCatalogItemRequest\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\x11DeleteCatalogItem\x12!.catalog.DeleteCatalogItemRequest\x1a\x16.google.protobuf.EmptyB\x1eZ\x1cshared/proto/catalog;catalogb\x06proto3"

var (
	file_catalog_proto_rawDescOnce sync.Once
	file_catalog_proto_rawDescData []byte
)

func file_catalog_proto_rawDescGZIP() []byte {
	file_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)))
	})
	return file_catalog_proto_rawDescData
}

var file_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_catalog_proto_goTypes = []any{
	(*GetCatalogItemsResponse)(nil),  // 0: catalog.GetCatalogItemsResponse
	(*UpdateCatalogItemRequest)(nil), // 1: catalog.UpdateCatalogItemRequest
	(*CreateCatalogItemRequest)(nil), // 2: catalog.CreateCatalogItemRequest
	(*DeleteCatalogItemRequest)(nil), // 3: catalog.DeleteCatalogItemRequest
	(*CatalogItem)(nil),              // 4: catalog.CatalogItem
	(*emptypb.Empty)(nil),            // 5: google.protobuf.Empty
}
var file_catalog_proto_depIdxs = []int32{
	4, // 0: catalog.GetCatalogItemsResponse.items:type_name -> catalog.CatalogItem
	4, // 1: catalog.UpdateCatalogItemRequest.item:type_name -> catalog.CatalogItem
	4, // 2: catalog.CreateCatalogItemRequest.item:type_name -> catalog.CatalogItem
	5, // 3: catalog.CatalogService.GetCatalogItems:input_type -> google.protobuf.Empty
	1, // 4: catalog.CatalogService.UpdateCatalogItem:input_type -> catalog.UpdateCatalogItemRequest
	2, // 5: catalog.CatalogService.CreateCatalogItem:input_type -> catalog.CreateCatalogItemRequest
	3, // 6: catalog.CatalogService.DeleteCatalogItem:input_type -> catalog.DeleteCatalogItemRequest
	0, // 7: catalog.CatalogService.GetCatalogItems:output_type -> catalog.GetCatalogItemsResponse
	5, // 8: catalog.CatalogService.UpdateCatalogItem:output_type -> google.protobuf.Empty
	5, // 9: catalog.CatalogService.CreateCatalogItem:output_type -> google.protobuf.Empty
	5, // 10: catalog.CatalogService.DeleteCatalogItem:output_type -> google.protobuf.Empty
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_catalog_proto_init() }
func file_catalog_proto_init() {
	if File_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_proto_msgTypes,
	}.Build()
	File_catalog_proto = out.File
	file_catalog_proto_goTypes = nil
	file_catalog_proto_depIdxs = nil
}
