// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: profile.proto

package profile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProfileInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileInfo   *ProfileInfo           `protobuf:"bytes,1,opt,name=profileInfo,proto3" json:"profileInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileInfoResponse) Reset() {
	*x = GetProfileInfoResponse{}
	mi := &file_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileInfoResponse) ProtoMessage() {}

func (x *GetProfileInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileInfoResponse.ProtoReflect.Descriptor instead.
func (*GetProfileInfoResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileInfoResponse) GetProfileInfo() *ProfileInfo {
	if x != nil {
		return x.ProfileInfo
	}
	return nil
}

type GetProfileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileInfoRequest) Reset() {
	*x = GetProfileInfoRequest{}
	mi := &file_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileInfoRequest) ProtoMessage() {}

func (x *GetProfileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileInfoRequest.ProtoReflect.Descriptor instead.
func (*GetProfileInfoRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{1}
}

type UpdateProfileInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileInfoResponse) Reset() {
	*x = UpdateProfileInfoResponse{}
	mi := &file_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileInfoResponse) ProtoMessage() {}

func (x *UpdateProfileInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileInfoResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileInfoResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{2}
}

type UpdateProfileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileInfo   *ProfileInfo           `protobuf:"bytes,1,opt,name=profileInfo,proto3" json:"profileInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileInfoRequest) Reset() {
	*x = UpdateProfileInfoRequest{}
	mi := &file_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileInfoRequest) ProtoMessage() {}

func (x *UpdateProfileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileInfoRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProfileInfoRequest) GetProfileInfo() *ProfileInfo {
	if x != nil {
		return x.ProfileInfo
	}
	return nil
}

type ProfileInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProfileEmail    string                 `protobuf:"bytes,2,opt,name=profileEmail,proto3" json:"profileEmail,omitempty"`
	ProfilePhone    string                 `protobuf:"bytes,3,opt,name=profilePhone,proto3" json:"profilePhone,omitempty"`
	ProfileAddress  string                 `protobuf:"bytes,4,opt,name=profileAddress,proto3" json:"profileAddress,omitempty"`
	ProfileTitle    string                 `protobuf:"bytes,5,opt,name=profileTitle,proto3" json:"profileTitle,omitempty"`
	ProfileSubtitle string                 `protobuf:"bytes,6,opt,name=profileSubtitle,proto3" json:"profileSubtitle,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProfileInfo) Reset() {
	*x = ProfileInfo{}
	mi := &file_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileInfo) ProtoMessage() {}

func (x *ProfileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileInfo.ProtoReflect.Descriptor instead.
func (*ProfileInfo) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{4}
}

func (x *ProfileInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProfileInfo) GetProfileEmail() string {
	if x != nil {
		return x.ProfileEmail
	}
	return ""
}

func (x *ProfileInfo) GetProfilePhone() string {
	if x != nil {
		return x.ProfilePhone
	}
	return ""
}

func (x *ProfileInfo) GetProfileAddress() string {
	if x != nil {
		return x.ProfileAddress
	}
	return ""
}

func (x *ProfileInfo) GetProfileTitle() string {
	if x != nil {
		return x.ProfileTitle
	}
	return ""
}

func (x *ProfileInfo) GetProfileSubtitle() string {
	if x != nil {
		return x.ProfileSubtitle
	}
	return ""
}

var File_profile_proto protoreflect.FileDescriptor

const file_profile_proto_rawDesc = "" +
	"\n" +
	"\rprofile.proto\x12\aprofile\"P\n" +
	"\x16GetProfileInfoResponse\x126\n" +
	"\vprofileInfo\x18\x01 \x01(\v2\x14.profile.ProfileInfoR\vprofileInfo\"\x17\n" +
	"\x15GetProfileInfoRequest\"\x1b\n" +
	"\x19UpdateProfileInfoResponse\"R\n" +
	"\x18UpdateProfileInfoRequest\x126\n" +
	"\vprofileInfo\x18\x01 \x01(\v2\x14.profile.ProfileInfoR\vprofileInfo\"\xdb\x01\n" +
	"\vProfileInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\fprofileEmail\x18\x02 \x01(\tR\fprofileEmail\x12\"\n" +
	"\fprofilePhone\x18\x03 \x01(\tR\fprofilePhone\x12&\n" +
	"\x0eprofileAddress\x18\x04 \x01(\tR\x0eprofileAddress\x12\"\n" +
	"\fprofileTitle\x18\x05 \x01(\tR\fprofileTitle\x12(\n" +
	"\x0fprofileSubtitle\x18\x06 \x01(\tR\x0fprofileSubtitle2\xbf\x01\n" +
	"\x0eProfileService\x12Q\n" +
	"\x0eGetProfileInfo\x12\x1e.profile.GetProfileInfoRequest\x1a\x1f.profile.GetProfileInfoResponse\x12Z\n" +
	"\x11UpdateProfileInfo\x12!.profile.UpdateProfileInfoRequest\x1a\".profile.UpdateProfileInfoResponseB\x1eZ\x1cshared/proto/profile;profileb\x06proto3"

var (
	file_profile_proto_rawDescOnce sync.Once
	file_profile_proto_rawDescData []byte
)

func file_profile_proto_rawDescGZIP() []byte {
	file_profile_proto_rawDescOnce.Do(func() {
		file_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_proto_rawDesc), len(file_profile_proto_rawDesc)))
	})
	return file_profile_proto_rawDescData
}

var file_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_profile_proto_goTypes = []any{
	(*GetProfileInfoResponse)(nil),    // 0: profile.GetProfileInfoResponse
	(*GetProfileInfoRequest)(nil),     // 1: profile.GetProfileInfoRequest
	(*UpdateProfileInfoResponse)(nil), // 2: profile.UpdateProfileInfoResponse
	(*UpdateProfileInfoRequest)(nil),  // 3: profile.UpdateProfileInfoRequest
	(*ProfileInfo)(nil),               // 4: profile.ProfileInfo
}
var file_profile_proto_depIdxs = []int32{
	4, // 0: profile.GetProfileInfoResponse.profileInfo:type_name -> profile.ProfileInfo
	4, // 1: profile.UpdateProfileInfoRequest.profileInfo:type_name -> profile.ProfileInfo
	1, // 2: profile.ProfileService.GetProfileInfo:input_type -> profile.GetProfileInfoRequest
	3, // 3: profile.ProfileService.UpdateProfileInfo:input_type -> profile.UpdateProfileInfoRequest
	0, // 4: profile.ProfileService.GetProfileInfo:output_type -> profile.GetProfileInfoResponse
	2, // 5: profile.ProfileService.UpdateProfileInfo:output_type -> profile.UpdateProfileInfoResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_profile_proto_init() }
func file_profile_proto_init() {
	if File_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_proto_rawDesc), len(file_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_proto_goTypes,
		DependencyIndexes: file_profile_proto_depIdxs,
		MessageInfos:      file_profile_proto_msgTypes,
	}.Build()
	File_profile_proto = out.File
	file_profile_proto_goTypes = nil
	file_profile_proto_depIdxs = nil
}
