syntax = "proto3";

package catalog;

import "google/protobuf/empty.proto";

option go_package = "shared/proto/catalog;catalog";

service CatalogService {
  rpc GetCatalogItems(google.protobuf.Empty) returns (GetCatalogItemsResponse);
  rpc UpdateCatalogItem(UpdateCatalogItemRequest) returns (google.protobuf.Empty);
  rpc CreateCatalogItem(CreateCatalogItemRequest) returns (google.protobuf.Empty);
  rpc DeleteCatalogItem(DeleteCatalogItemRequest) returns (google.protobuf.Empty);
}

message GetCatalogItemsResponse {
  repeated CatalogItem items = 1;
}
message UpdateCatalogItemRequest {
  CatalogItem item = 1;
}
message CreateCatalogItemRequest {
  CatalogItem item = 1;
}
message DeleteCatalogItemRequest {
  string id = 1;
}

message CatalogItem {
  string id = 1;
  string title = 2;
  string category = 3;
  string imgUrl = 4;
}
